# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/matthewjones/Dropbox/Development/spotifyripper-gui/interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1280, 751)
        mainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.results = QtGui.QTableWidget(self.centralwidget)
        self.results.setMaximumSize(QtCore.QSize(1256, 16777215))
        self.results.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.results.setObjectName(_fromUtf8("results"))
        self.results.setColumnCount(6)
        self.results.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.results.setHorizontalHeaderItem(5, item)
        self.results.horizontalHeader().setDefaultSectionSize(100)
        self.results.horizontalHeader().setSortIndicatorShown(True)
        self.results.verticalHeader().setMinimumSectionSize(15)
        self.results.verticalHeader().setSortIndicatorShown(False)
        self.gridLayout.addWidget(self.results, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.overall_progress = QtGui.QProgressBar(self.centralwidget)
        self.overall_progress.setProperty("value", 0)
        self.overall_progress.setObjectName(_fromUtf8("overall_progress"))
        self.horizontalLayout_3.addWidget(self.overall_progress)
        self.gridLayout.addLayout(self.horizontalLayout_3, 9, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.search_options = QtGui.QComboBox(self.centralwidget)
        self.search_options.setObjectName(_fromUtf8("search_options"))
        self.search_options.addItem(_fromUtf8(""))
        self.search_options.addItem(_fromUtf8(""))
        self.search_options.addItem(_fromUtf8(""))
        self.search_options.addItem(_fromUtf8(""))
        self.search_options.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.search_options)
        self.search_bar = QtGui.QLineEdit(self.centralwidget)
        self.search_bar.setObjectName(_fromUtf8("search_bar"))
        self.horizontalLayout.addWidget(self.search_bar)
        self.search_button = QtGui.QPushButton(self.centralwidget)
        self.search_button.setObjectName(_fromUtf8("search_button"))
        self.horizontalLayout.addWidget(self.search_button)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.track_progress = QtGui.QProgressBar(self.centralwidget)
        self.track_progress.setProperty("value", 0)
        self.track_progress.setObjectName(_fromUtf8("track_progress"))
        self.horizontalLayout_2.addWidget(self.track_progress)
        self.gridLayout.addLayout(self.horizontalLayout_2, 7, 0, 1, 1)
        self.download_all_songs_button = QtGui.QPushButton(self.centralwidget)
        self.download_all_songs_button.setObjectName(_fromUtf8("download_all_songs_button"))
        self.gridLayout.addWidget(self.download_all_songs_button, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout.addWidget(self.groupBox, 3, 0, 1, 1)
        self.current_download = QtGui.QLabel(self.centralwidget)
        self.current_download.setObjectName(_fromUtf8("current_download"))
        self.gridLayout.addWidget(self.current_download, 4, 0, 2, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuSpotify_Ripper = QtGui.QMenu(self.menubar)
        self.menuSpotify_Ripper.setObjectName(_fromUtf8("menuSpotify_Ripper"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.actionSpotify_Login_Details = QtGui.QAction(mainWindow)
        self.actionSpotify_Login_Details.setObjectName(_fromUtf8("actionSpotify_Login_Details"))
        self.actionDownload_Preferences = QtGui.QAction(mainWindow)
        self.actionDownload_Preferences.setObjectName(_fromUtf8("actionDownload_Preferences"))
        self.menuSpotify_Ripper.addAction(self.actionSpotify_Login_Details)
        self.menuSpotify_Ripper.addAction(self.actionDownload_Preferences)
        self.menubar.addAction(self.menuSpotify_Ripper.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Spotify Ripper", None))
        self.results.setSortingEnabled(True)
        item = self.results.horizontalHeaderItem(0)
        item.setText(_translate("mainWindow", "URI", None))
        item = self.results.horizontalHeaderItem(1)
        item.setText(_translate("mainWindow", "Song", None))
        item = self.results.horizontalHeaderItem(2)
        item.setText(_translate("mainWindow", "Artist", None))
        item = self.results.horizontalHeaderItem(3)
        item.setText(_translate("mainWindow", "Album", None))
        item = self.results.horizontalHeaderItem(4)
        item.setText(_translate("mainWindow", "Duration", None))
        item = self.results.horizontalHeaderItem(5)
        item.setText(_translate("mainWindow", "Download", None))
        self.label_3.setText(_translate("mainWindow", "Overall Progress", None))
        self.search_options.setItemText(0, _translate("mainWindow", "Keyword(s)", None))
        self.search_options.setItemText(1, _translate("mainWindow", "Track", None))
        self.search_options.setItemText(2, _translate("mainWindow", "Artist", None))
        self.search_options.setItemText(3, _translate("mainWindow", "Album", None))
        self.search_options.setItemText(4, _translate("mainWindow", "Playlist", None))
        self.search_bar.setToolTip(_translate("mainWindow", "<html><head/><body><p>Enter</p><p><br/></p></body></html>", None))
        self.search_button.setText(_translate("mainWindow", "Search", None))
        self.label_2.setText(_translate("mainWindow", "Track Progress   ", None))
        self.download_all_songs_button.setText(_translate("mainWindow", "Download All Songs", None))
        self.groupBox.setTitle(_translate("mainWindow", "Download Progress", None))
        self.current_download.setText(_translate("mainWindow", "Currently Downloading: N/A", None))
        self.menuSpotify_Ripper.setTitle(_translate("mainWindow", "Preferences", None))
        self.actionSpotify_Login_Details.setText(_translate("mainWindow", "Spotify Login Details", None))
        self.actionDownload_Preferences.setText(_translate("mainWindow", "Download Preferences", None))

